all_districts = {
    "Toshkent shahri": [
        "Olmazor tumani",
        "Bektemir tumani",
        "Mirobod tumani",
        "Mirzo-Ulug'bek tumani",
        "Sergeli tumani",
        "Shayxontohur tumani",
        "Yunusobod tumani",
        "Yakkasaroy tumani",
        "Chilonzor tumani",
        "Yashnobod tumani",
        "Uchtepa tumani"
    ],
    "Toshkent viloyati": [
        "Angren shahri",
        "Bekobod shahri",
        "Chinoz tumani",
        "Oqqo'rg'on tumani",
        "Ohangaron tumani",
        "Piskent tumani",
        "Parkent tumani",
        "Bo'stonliq tumani",
        "Bekobod tumani",
        "Zangiota tumani",
        "Quyichirchiq tumani",
        "O'rta Chirchiq tumani",
        "Yangiyo'l tumani",
        "Yuqori Chirchiq tumani",
        "Nurafshon shahri"
    ],
    "Namangan viloyati": [
        "Namangan shahri",
        "Chortoq tumani",
        "Kosonsoy tumani",
        "Mingbuloq tumani",
        "Namangan tumani",
        "Norin tumani",
        "Pop tumani",
        "To‘raqo‘rg‘on tumani",
        "Uchqo‘rg‘on tumani",
        "Uychi tumani",
        "Yangiqo‘rg‘on tumani"
    ],
    "Farg'ona viloyati": [
        "Farg‘ona shahri",
        "Beshariq tumani",
        "Bog‘dod tumani",
        "Buvayda tumani",
        "Dang‘ara tumani",
        "Farg‘ona tumani",
        "Furqat tumani",
        "Oltiariq tumani",
        "Quva tumani",
        "Quvasoy shahri",
        "Rishton tumani",
        "So‘x tumani",
        "Toshloq tumani",
        "Uchko‘prik tumani",
        "Yozyovon tumani"
    ],
    "Sirdaryo viloyati": [
        "Guliston shahri",
        "Boyovut tumani",
        "Guliston tumani",
        "Mirzaobod tumani",
        "Oqoltin tumani",
        "Sardoba tumani",
        "Sayxunobod tumani",
        "Shirin shahri",
        "Sirdaryo tumani",
        "Yangiyer shahri"
    ],
    "Xorazm viloyati": [
        "Urganch shahri",
        "Bog‘ot tumani",
        "Gurlan tumani",
        "Xazorasp tumani",
        "Xiva tumani",
        "Xonqa tumani",
        "Qo‘shko‘pir tumani",
        "Shovot tumani",
        "Yangiariq tumani",
        "Yangibozor tumani"
    ],
    "Jizzax viloyati": [
        "Jizzax shahri",
        "Arnasoy tumani",
        "Baxmal tumani",
        "Do‘stlik tumani",
        "Forish tumani",
        "G‘allaorol tumani",
        "Jizzax tumani",
        "Mirzacho‘l tumani",
        "Paxtakor tumani",
        "Yangiobod tumani",
        "Zafarobod tumani",
        "Zarbdor tumani"
    ],
    "Surxondaryo viloyati": [
        "Termiz shahri",
        "Angor tumani",
        "Bandixon tumani",
        "Boysun tumani",
        "Denov tumani",
        "Jarqo‘rg‘on tumani",
        "Muzrabot tumani",
        "Oltinsoy tumani",
        "Qiziriq tumani",
        "Qumqo‘rg‘on tumani",
        "Sariosiyo tumani",
        "Sherobod tumani",
        "Sho‘rchi tumani",
        "Termiz tumani",
        "Uzun tumani"
    ],
    "Qashqadaryo viloyati": [
        "Qarshi shahri",
        "Chiroqchi tumani",
        "Dehqonobod tumani",
        "G‘uzor tumani",
        "Kasbi tumani",
        "Kitob tumani",
        "Koson tumani",
        "Miriqishloq tumani",
        "Muborak tumani",
        "Nishon tumani",
        "Qamashi tumani",
        "Shahrisabz tumani",
        "Yakkabog‘ tumani"
    ],
    "Navoiy viloyati": [
        "Navoiy shahri",
        "Karmana tumani",
        "Konimex tumani",
        "Qiziltepa tumani",
        "Navbahor tumani",
        "Nurota tumani",
        "Uchquduq tumani",
        "Xatirchi tumani",
        "Zarafshon shahri"
    ],
    "Buxoro viloyati": [
        "Buxoro shahri",
        "Alat tumani",
        "Buxoro tumani",
        "G‘ijduvon tumani",
        "Jondor tumani",
        "Kogon shahri",
        "Kogon tumani",
        "Olot tumani",
        "Peshku tumani",
        "Qorako‘l tumani",
        "Qorovulbozor tumani",
        "Romitan tumani",
        "Shofirkon tumani",
        "Vobkent tumani"
    ],
    "Samarqand viloyati": [
        "Samarqand shahri",
        "Bulung‘ur tumani",
        "Ishtixon tumani",
        "Jomboy tumani",
        "Kattaqo‘rg‘on shahri",
        "Kattaqo‘rg‘on tumani",
        "Narpay tumani",
        "Nurobod tumani",
        "Oqdaryo tumani",
        "Payariq tumani",
        "Pastdarg‘om tumani",
        "Paxtachi tumani",
        "Qo‘shrabot tumani",
        "Samarqand tumani",
        "Toyloq tumani",
        "Urgut tumani"
    ],
    "Andijon viloyati": [
        "Andijon shahri",
        "Andijon tumani",
        "Asaka tumani",
        "Baliqchi tumani",
        "Bo‘z tumani",
        "Buloqboshi tumani",
        "Izboskan tumani",
        "Jalaquduq tumani",
        "Marhamat tumani",
        "Oltinko‘l tumani",
        "Paxtaobod tumani",
        "Qo‘rg‘ontepa tumani",
        "Shahrixon tumani",
        "Ulug‘nor tumani",
        "Xo‘jaobod tumani"
    ],
    "Qoraqalpog'iston": [
        "Nukus shahri",
        "Amudaryo tumani",
        "Beruniy tumani",
        "Chimboy tumani",
        "Ellikqala tumani",
        "Kegeyli tumani",
        "Mo‘ynoq tumani",
        "Nukus tumani",
        "Qonliko‘l tumani",
        "Qorao‘zak tumani",
        "Shumanay tumani",
        "Taxiatosh shahri",
        "Taxtako‘pir tumani",
        "To‘rtko‘l tumani",
        "Xo‘jayli tumani"
    ],
}