# Generated by Django 5.0.6 on 2024-05-11 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_id', models.UUIDField(default=uuid.uuid4, verbose_name='Olimpiada ID')),
                ('olympiad_name', models.CharField(max_length=255, verbose_name='Olimpiada nomi')),
                ('olympiad_description', models.TextField(verbose_name="Olimpiada haqida ma'lumot")),
                ('olympiad_science', models.CharField(max_length=255, verbose_name='Olimpiada fani')),
                ('olympiad_price', models.IntegerField(verbose_name='Olimpiada narxi')),
                ('olympiad_start_datetime', models.DateTimeField(verbose_name='Olimpiada boshlanish vaqti')),
                ('olympiad_duration_minutes', models.IntegerField(verbose_name='Olimpiada davomiyligi')),
                ('olympiad_stop_datetime', models.DateTimeField(verbose_name='Olimpiada tugash vaqti')),
                ('allow_classes', models.CharField(max_length=255, verbose_name='Qaysi sinflar qatnasha olishadi??? (Misol uchun [1, 2, 3])')),
            ],
            options={
                'verbose_name': 'Olimpiada',
                'verbose_name_plural': 'Olimpiadalar',
                'db_table': 'olympiads',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('datetime', models.DateTimeField(verbose_name='Sana va vaqti')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('olympiad_id', models.IntegerField(verbose_name='Olimpiada ID')),
                ('olympiad_name', models.CharField(max_length=255, verbose_name='Olimpiada nomi')),
                ('olympiad_start_datetime', models.DateTimeField(verbose_name='Olimpiada boshlanish vaqti')),
                ('olympiad_stop_datetime', models.DateTimeField(verbose_name='Olimpiada tugash vaqti')),
                ('right_answers_count', models.IntegerField(verbose_name="To'g'ri javoblar soni")),
                ('wrong_answers_count', models.IntegerField(verbose_name='Xato javoblar soni')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="Foydalanuvchi to'liq ismi")),
                ('created_at', models.DateTimeField(verbose_name='Sana va vaqti')),
                ('olympiad_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.olympiads', verbose_name='Olimpiada nomi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_question', models.TextField(verbose_name='Savol')),
                ('test_variant_1', models.CharField(max_length=255, verbose_name='Variant 1')),
                ('test_variant_2', models.CharField(max_length=255, verbose_name='Variant 2')),
                ('test_variant_3', models.CharField(max_length=255, verbose_name='Variant 3')),
                ('test_variant_4', models.CharField(max_length=255, verbose_name='Variant 4')),
                ('test_correct_variant', models.CharField(max_length=255, verbose_name="To'g'ri javob (to'liq)")),
                ('test_olympiad_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.olympiads', verbose_name='Olimpiada nomi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('province', models.CharField(max_length=255, verbose_name='Viloyati')),
                ('city', models.CharField(max_length=255, verbose_name='Shahar/Tumani')),
                ('school', models.IntegerField(verbose_name='Maktab raqami')),
                ('school_class', models.IntegerField(verbose_name='Sinf raqami')),
                ('balance', models.IntegerField(default=0, verbose_name='Balans')),
                ('olympiad_ids', models.ManyToManyField(blank=True, to='admin_panel.olympiads', verbose_name='Olimpiadalar')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
